androidboot.hardware=qcom
androidboot.bootdevice=7824900.sdhci
androidboot.selinux=permissive
buildvariant=userdebug
msm_rtb.filter=0x237
ehci-hcd.park=3
lpm_levels.sleep_disabled=1
loop.max_part=7
loglevel=7
ignore_loglevel
printk.time=1
pmos.nosplash
pmos.log
